theme: jekyll-theme-cayman

title: "C++ Library for Responsibility Sensitive Safety"
show_downloads: "true"

github:
  zip_url: https://github.com/intel/ad-rss-lib/archive/master.zip
  tar_url: https://github.com/intel/ad-rss-lib/archive/master.tar.gz

defaults:

  -
    scope:
      path: ""
    values:
      layout: "default"
